#ifndef CUSTOM_JOB_OBJECT_MSGS_H
#define CUSTOM_JOB_OBJECT_MSGS_H

#define CUSTOM_JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT (10000 + JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT)
#define CUSTOM_JOB_OBJECT_MSG_JOB_MEMORY_LIMIT (10000 + JOB_OBJECT_MSG_JOB_MEMORY_LIMIT)
#define CUSTOM_JOB_OBJECT_MSG_END_OF_JOB_TIME (10000 + JOB_OBJECT_MSG_END_OF_JOB_TIME)
#define CUSTOM_JOB_OBJECT_MSG_END_OF_PROCESS_TIME (10000 + JOB_OBJECT_MSG_END_OF_PROCESS_TIME)

#endif // CUSTOM_JOB_OBJECT_MSGS_H