#ifndef defines_H
#define defines_H

#define WIN32_LEAN_AND_MEAN
#define NOCOMM
#define WINVER 0x0500

#define NTSTATUS_STATUS_SUCCESS 0
#define NTSTATUS_STATUS_ACCESS_DENIED 0xC0000022
#define CUSTOM_EXIT_CODE_TERMINATED_BY_CHECKER 0xFF000001
#define CUSTOM_EXIT_CODE_WRONG_SCANF_FORMAT 3

#define CUSTOM_JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT (10000 + JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT)
#define CUSTOM_JOB_OBJECT_MSG_JOB_MEMORY_LIMIT (10000 + JOB_OBJECT_MSG_JOB_MEMORY_LIMIT)
#define CUSTOM_JOB_OBJECT_MSG_END_OF_JOB_TIME (10000 + JOB_OBJECT_MSG_END_OF_JOB_TIME)
#define CUSTOM_JOB_OBJECT_MSG_END_OF_PROCESS_TIME (10000 + JOB_OBJECT_MSG_END_OF_PROCESS_TIME)
#define CUSTOM_JOB_OBJECT_MSG_END_OF_IDLENESS (10000)

#endif // defines_H